### ISSUE TITLE
Migration to Gazebo 9 / ROS melodic

### ISSUE THREAD

**Issue by Arpafaucon** [wuwushrek/sim_cf#2]
The current code base is usable with gazebo 7 only.  
I'm opening the current issue to think about ways to (elegantly) make it usable with gazebo 9 as well, and track the overall progress

#### Migration guide
https://bitbucket.org/osrf/gazebo/src/default/Migration.md?fileviewer=file-view-default
#### API docs
http://osrf-distributions.s3.amazonaws.com/gazebo/api/1.4.0/namespacegazebo.html
https://ignitionrobotics.org/api/math/4.0/annotated.html

## Proposed migration
- [x] find a proper way to detect current Gazebo version
```cpp
#define GAZEBO_9 (GAZEBO_MAJOR_VERSION >= 9)
```
- [x] use `ignition::math` instead of `gazebo::math`
  - [x] `gazebo::math::Vector3` -> `ignition::math::Vector3`
  - [x] same with `Pose3` -> `Pose3d`
- [x] change getters/setters `GetX()` to `X()`
- [x] Events are automatically disconnected when deleted in v9, remove `events::Events::Disconnect***()` from destructors

### Notes
`gazebo::math::Vector3` implicitely contains doubles, that is not the case of `ignition::math::Vector3`. The closest translation is `Vector3d`

**Comment by Arpafaucon** [comment]
To ease transition, `GazeboWindPlugin` typedef's as `V3` the correct Vector type. That smoothens a lot the migration without harming readability:
```cpp
// old
math::Vector3 x;
//new 
V3 x;
```

**Comment by Arpafaucon** [comment]
@wuwushrek  could you provide your current code formatting settings? I nearly finished the migration, but I had to reformat some files, and that messes up the Commit (not a lot, just making it less readable)

**Comment by Arpafaucon** [comment]
started PR #3 
Do NOT merge yet ! But feel free to check if the code compiles gracefully on Kinetic :smile:

**Comment by wuwushrek** [comment]
@Arpafaucon Thanks ! about the formatting settings, I didn't pay too much attention to that. You will probably find different formatting settings for different files so do what you feel appropriate for that ;) coming back to you as soon as I test it on kinetic !

**Comment by wuwushrek** [comment]
@Arpafaucon  I got some problems while compiling your migration.

The first are related to any of these inclusions : 
`#include <gazebo/Math/Vector3.hh>`
`#include <gazebo/Math/Pose.hh>`
There are no such files in gazebo7 (for kinetic). The class Vector3 and Pose are contained in gazebo::math so you don't need to include them. They can be directly used by math::Vector3 or math::Pose if you are in gazebo namespace.

The second problem is : 
`typedef math::Pose3 P3;`
Pose3 doesn't exist in gazebo::math however math::Pose do exist and is prob what you want !

I just noticed I am also able to use ignition::math in my gazebo7 [here](https://github.com/wuwushrek/sim_cf/blob/3374d65b12678c316c2502561b4c535840a79434/crazyflie_gazebo/include/gazebo_cfGhost_plugin.h#L50) so maybe you can directly change any math::Vector3 to ignition::Vector3 ? A coma is also missing [here](https://github.com/Arpafaucon/sim_cf/blob/8c1db3c5c379b4a8cc82b79039fc1c5f6e082e88/crazyflie_gazebo/include/gazebo_cfGhost_plugin.h#L59)

Since you also have defined P3 and V3, I see that most of the time they are only used when gazebo_9 is defined, maybe to have something more uniform you want to use them in the other cases ?  Like for example [here](https://github.com/Arpafaucon/sim_cf/blob/8c1db3c5c379b4a8cc82b79039fc1c5f6e082e88/crazyflie_gazebo/src/gazebo_odometry_plugin.cpp#L296-L301). there are other files like this.

**Comment by Arpafaucon** [comment]
thanks for the feedback !
1. the first includes are (what I thought was necessary) for Gazebo 7. I was wrong, they are defined in `gazebo/math/gzmath.hh`. I will include that file instead
2. that is indeed `math::Pose` after checking
3. changing to ignition::math can be done in inner computations, but the Gazebo API should not accept them in v7. To keep it simple while migrating I only used gazebo::math in v7 
4. semicolon corrected

these issues are addressed in https://github.com/Arpafaucon/sim_cf/commit/4446fa59678f20b29b2b8eeab66e7c35ce86b65c

5. In the case you linked, the API function have also changed, otherwise I wouldn't have needed the `#if`. I see your point, though, and will do a commit about that

[EDIT] commit updated, see : https://github.com/Arpafaucon/sim_cf/commit/4d63b10d07d70fbde3b4a6b82149e76abc59ed62

**Comment by Arpafaucon** [comment]
Did a simulation with `test_high_level.py` and one drone.  All seems to work well :smile: 

Do you want me to test anything special ?

**Comment by wuwushrek** [comment]
Almost there : 
 1.  just typo mistakes on [these lines](https://github.com/Arpafaucon/sim_cf/blob/4d63b10d07d70fbde3b4a6b82149e76abc59ed62/crazyflie_gazebo/include/gazebo_wind_plugin.h#L70-L73). migr_math::Vector3 -> math::Vector3.
 2. Since  [here](https://github.com/Arpafaucon/sim_cf/blob/4d63b10d07d70fbde3b4a6b82149e76abc59ed62/crazyflie_gazebo/include/gazebo_cfGhost_plugin.h#L63) you are using P3 as math::Pose (I was actually using ignition::math::Pose3d for this specific file) which doesn't have the constructor with the quaternion values qw,...,qx (constructor I was actually using),  A good migration can be to do the following changes : 
        -> [these lines](https://github.com/Arpafaucon/sim_cf/blob/4d63b10d07d70fbde3b4a6b82149e76abc59ed62/crazyflie_gazebo/src/gazebo_cfGhost_plugin.cpp#L51-L57) into `last_pose = P3(model_->WorldPose());`
        -> [these lines](https://github.com/Arpafaucon/sim_cf/blob/4d63b10d07d70fbde3b4a6b82149e76abc59ed62/crazyflie_gazebo/src/gazebo_cfGhost_plugin.cpp#L59-L65) into `last_pose = P3(model_->GetWorldPose());`
        -> [these lines](https://github.com/Arpafaucon/sim_cf/blob/4d63b10d07d70fbde3b4a6b82149e76abc59ed62/crazyflie_gazebo/src/gazebo_cfGhost_plugin.cpp#L92-L98) into `last_pose = P3(position->values[0],position->values[1],position->values[2],0,0,0);` Note that I'm not using the constructor with quaternion here. These should fix this file.
 3. I think this is all

**Comment by Arpafaucon** [comment]
OK:
https://github.com/Arpafaucon/sim_cf/commit/139319c250e064d98ad6b2e285dc99f18edc8b0a should bring the needed corrections. 
I will test more deeply this morning

**Comment by Arpafaucon** [comment]
feedback on friday testing : 
- got a `runtime_error -> timeout` on a obviously wrong call (bad drone URI). If possible, that might be interesting to see if the message can be made more explicit
- after that, ghosting mode started fine. However, when the drone first loses temporarily radio connection, location topic silently stop updating
- simulation went fine

**Comment by Arpafaucon** [comment]
So I believe you can merge without risks now, if you haven't noticed any issues

**Comment by wuwushrek** [comment]
@Arpafaucon  thanks for the feedback. 
Before merging there is still one more problem :  [migr::math hasn't been removed from the constructor here](https://github.com/Arpafaucon/sim_cf/blob/139319c250e064d98ad6b2e285dc99f18edc8b0a/crazyflie_gazebo/include/gazebo_wind_plugin.h#L71).
Do you want me to update the doc with information about melodic setup with gazebo9 or is it useless ?

- About the time-out issue, if the url is specified in the good format, yes it won't be able to tell you if actually there exists a cf at the other end. I can throw an error when trying for some time to connect to the cf and it fails. This error will be synonym of non-connected cf. Is it fine ?
- I don't understand very well the problem with the ghosting mode ?

**Comment by Arpafaucon** [comment]
1. my bad for the `migr_math` I thought I already commited that. Commit https://github.com/Arpafaucon/sim_cf/commit/c0744d78d68213eb7624d02ba4f5504d21f8d18f is online

2. OK. It could be useful for the end-user to have some advice about this error ( a more descriptive error message) 

3. in ghosting mode , if I move the drone in the room, at some point the position stops being updated (topic, and visually on gazebo), and the problem persists until I restart `crazyflie_server` (bringing the drone close to the radio again is not enough)
