### ISSUE TITLE
dynamic model instabilities when simulation time fluctuates

### ISSUE THREAD

**Issue by Arpafaucon** [wuwushrek/sim_cf#8]
# Context
I observe drone instabilities:
- if I pause then resume the simulation
- if I move gazebo client 3D view a lot

Drones have trouble staying in place, and eventually crash into the ground

I believe that might be related to some *time integration issues*.

**Comment by wuwushrek** [comment]
Thanks for the notifications.
 - Well my initial implementation didn't take in account that scenario. But the problem is most likely due to the fact that when you pause simulation, update function is not executed anymore and no sensors information (lps, imu etc...) are sent to the crazyflie and therefore his estimator just diverges. When you do play, it's prob too late. I can fix that but DO we need to ? Basically a solution will be to keep sending the last saved sensors state in pause mode and reset the kalman estimator on play mode (actually just resetting it should be sufficient). Note that if you do a pause the cf is on the ground there should be no problem...
 - For gazebo client 3D view, I can't see why yet. It should not influence the simulation as long as you are not pausing or removing the cf models

**Comment by Arpafaucon** [comment]
Update after tests in the lab :
I haven't observed any of the two problems on the lab computer. Pausing for up to 30 secs works fine...
I guess that is a problem that comes with lower tier computers (the one in the lab : 40 cores, 64Go RAM)
Without more infos, I don't see what we could do.

Regarding the question "do we need it", that allows me to alleviate the computationnal load between experiments.Once again, that's not imperatively needed.
